const filters = {
  genres: [
    { value: 'Action', label: 'Action', },
    { value: 'Adventure', label: 'Adventure' },
    { value: 'Cars', label: 'Cars' },
    { value: 'Comedy', label: 'Comedy' },
    { value: 'Drama', label: 'Drama' },
    { value: 'Fantasy', label: 'Fantasy' },
    { value: 'Horrow', label: 'Horrow' },
    { value: 'Mahou Shojou', label: 'Mahou Shojou' },
    { value: 'Mecha', label: 'Mecha' },
    { value: 'Music', label: 'Music' },
    { value: 'Mystery', label: 'Mystery' },
    { value: 'Psychological', label: 'Psychological' },
    { value: 'Romace', label: 'Romace' },
    { value: 'Sci-Fi', label: 'Sci-Fi' },
    { value: 'Slice of Life', label: 'Slice of Life' },
    { value: 'Sports', label: 'Sports' },
    { value: 'Supernatural', label: 'Supernatural' },
    { value: 'Thriller', label: 'Thriller' },
  ],
  seasons: [
    { value: 'WINTER', label: 'WINTER' },
    { value: 'SPRING', label: 'SPRING' },
    { value: 'SUMMER', label: 'SUMMER' },
    { value: 'FALL', label: 'FALL' },
  ],
  formats: [
    { value: 'TV', label: 'TV'},
    { value: 'MOVIE', label: 'MOVIE'},
    { value: 'TV_SHORT', label: 'TV_SHORT'},
    { value: 'SPECIAL', label: 'SPECIAL'},
    { value: 'OVA', label: 'OVA'},
    { value: 'ONA', label: 'ONA'},
    { value: 'MUSIC', label: 'MUSIC'}
  ],
  years: [
    { value: 2023, label: 2023 },
    { value: 2022, label: 2022 },
    { value: 2021, label: 2021 },
    { value: 2020, label: 2020 },
    { value: 2019, label: 2019 },
    { value: 2018, label: 2018 },
    { value: 2017, label: 2017 },
    { value: 2016, label: 2016 },
    { value: 2015, label: 2015 },
    { value: 2014, label: 2014 },
    { value: 2013, label: 2013 },
    { value: 2012, label: 2012 },
    { value: 2011, label: 2011 },
    { value: 2010, label: 2010 },
  ]
}

export default filters